# syntax=docker/dockerfile:experimental
# To pull this image, create an account and login according to
# this SO post:
#    https://stackoverflow.com/a/70970425

# Jetpack 4.5 (the Jetpack version on our dog)
# FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3

# Jetpack 4.6 (from gmargo, Walk These Ways)
# FROM nvcr.io/nvidia/l4t-pytorch:r32.6.1-pth1.9-py

# Jetpack 4.6.1 (the last Jetpack version before 5)
FROM nvcr.io/nvidia/l4t-pytorch:r32.7.1-pth1.10-py3

# Jetpack 5.0.2 (from geyang, Go1 Setup Guide)
# FROM nvcr.io/nvidia/l4t-pytorch:r35.1.0-pth1.13-py3
